# flaskit/cli.py
import platform
import subprocess
import shutil
from pathlib import Path
import typer
from rich.console import Console
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn
from rich.panel import Panel
from flaskit.generator import Generator

console = Console()
app = typer.Typer(help="🚀 FlaskIt — Flask Project Generator CLI \n Just flask it")


def complete_template(incomplete: str):
    for name in ("mvp", "saas"):
        if name.startswith(incomplete):
            yield name


def complete_db(incomplete: str):
    for name in ("sqlite", "postgresql"):
        if name.startswith(incomplete):
            yield name


@app.command()
def create(
    project_name: str = typer.Argument(..., help="Project root folder"),
    template: str = typer.Option("mvp", help="Template: mvp or saas", autocompletion=complete_template),
    gitignore: bool = typer.Option(False, "--gitignore", is_flag=True, help="Include .gitignore"),
    readme: bool = typer.Option(False, "--readme", is_flag=True, help="Include README.md"),
    dockerfile: bool = typer.Option(False, "--dockerfile", is_flag=True, help="Include Dockerfile"),
    env_file: bool = typer.Option(False, "--env-file", is_flag=True, help="Include .env"),
    db: str = typer.Option("sqlite", help="Database: sqlite or postgresql", autocompletion=complete_db),
    vscode: bool = typer.Option(False, "--vscode", is_flag=True, help="Open project in VS Code after creation"),
):
    """Create a Flask project skeleton with full MVP or SAAS structure"""
    template = template.lower()
    if template not in ("mvp", "saas"):
        console.print(f"[yellow]⚠️ Unknown template '{template}', defaulting to 'mvp'[/]")
        template = "mvp"

    if db not in ("sqlite", "postgresql"):
        console.print(f"[yellow]⚠️ Unknown db '{db}', defaulting to 'sqlite'[/]")
        db = "sqlite"

    entry_point = "main.py" if template == "mvp" else "run.py"
    root = Path(project_name).resolve()
    console.print(Panel(f"🌱 Creating project [bold cyan]{project_name}[/] using [bold yellow]{template.upper()}[/] template", expand=False))

    generator = Generator(root)

    # Progress for folders/files
    with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), BarColumn(), TimeElapsedColumn(), console=console) as progress:
        task = progress.add_task("Generating project...", total=1)
        if template.lower() == "mvp":
            generator.generate_mvp()
        else:
            generator.generate_saas(db)
        progress.update(task, advance=1)

    # Extra optional files
    if gitignore:
        generator.write_file(root / ".gitignore", "__pycache__/\n.env\ninstance/\n*.pyc\n")
    if readme:
        generator.write_file(root / "README.md", f"# {project_name}\n\nGenerated by FlaskIt CLI.\n")
    if dockerfile:
        generator.write_file(root / "Dockerfile", f"FROM python:3.10-slim\nWORKDIR /{project_name}\nCOPY . .\nRUN pip install -r requirements.txt\nCMD [\"python\", \"{entry_point}\"]\n")
    if env_file:
        db_line = "DB_URL=postgresql://username:password@localhost:5432/dbname" if db=="postgresql" else "DB_URL=sqlite:///app.db"
        generator.write_file(root / ".env", f"FLASK_APP={entry_point}\nFLASK_ENV=development\n{db_line}\n")

    # Rich table summary
    table = Table(title="Generated Items")
    table.add_column("Type")
    table.add_column("Path")
    for emoji, path in generator.generated_items:
        table.add_row(emoji, path)
    console.print(table)

    console.print(Panel(f"✅ Project [bold cyan]{project_name}[/] ready! Start coding!", style="green"))
    console.print(f"Next steps:\n  cd {project_name}\n  pip install -r requirements.txt\n  python {'main.py' if template=='mvp' else 'run.py'}")

    if vscode:
        # code = standard, code-oss = OSS builds on Linux, codium = VSCodium
        code_path = None
        for cmd in ("code", "code-oss", "codium"):
            code_path = shutil.which(cmd)
            if code_path:
                break
        if code_path:
            console.print(f"\n[bold cyan]Opening {project_name} in VS Code...[/]")
            if platform.system() == "Windows":
                subprocess.Popen(f'"{code_path}" "{root}"', shell=True)
            else:
                subprocess.Popen([code_path, str(root)])
        else:
            console.print("\n[yellow]⚠️ VS Code command not found. Looked for: code, code-oss, codium.[/]")
            console.print("[yellow]  Install VS Code and ensure it's on your PATH.[/]")

if __name__ == "__main__":
    app()
