# flaskit/cli.py
import os
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TextColumn,
    TimeElapsedColumn,
)
from rich.table import Table

from flaskit.generator import Generator

console = Console()
app = typer.Typer(help="🚀 FlaskIt — Flask Project Generator CLI \n Just flask it")


def complete_template(incomplete: str):
    for name in ("mvp", "saas"):
        if name.startswith(incomplete):
            yield name


def complete_db(incomplete: str):
    for name in ("sqlite", "postgresql"):
        if name.startswith(incomplete):
            yield name


@app.command()
def create(
    project_name: str = typer.Argument(..., help="Project root folder"),
    template: str = typer.Option(
        "mvp", help="Template: mvp or saas", autocompletion=complete_template
    ),
    gitignore: bool = typer.Option(
        False, "--gitignore", is_flag=True, help="Include .gitignore"
    ),
    readme: bool = typer.Option(
        False, "--readme", is_flag=True, help="Include README.md"
    ),
    dockerfile: bool = typer.Option(
        False, "--dockerfile", is_flag=True, help="Include Dockerfile"
    ),
    env_file: bool = typer.Option(
        False, "--env-file", is_flag=True, help="Include .env"
    ),
    db: str = typer.Option(
        "sqlite", help="Database: sqlite or postgresql", autocompletion=complete_db
    ),
    vscode: bool = typer.Option(
        False, "--vscode", is_flag=True, help="Open project in VS Code after creation"
    ),
):
    """Create a Flask project skeleton with full MVP or SAAS structure"""
    template = template.lower()
    if template not in ("mvp", "saas"):
        console.print(
            f"[yellow]⚠️ Unknown template '{template}', defaulting to 'mvp'[/]"
        )
        template = "mvp"

    if db not in ("sqlite", "postgresql"):
        console.print(f"[yellow]⚠️ Unknown db '{db}', defaulting to 'sqlite'[/]")
        db = "sqlite"

    entry_point = "main.py" if template == "mvp" else "run.py"
    root = Path(project_name).resolve()
    console.print(
        Panel(
            f"🌱 Creating project [bold cyan]{project_name}[/] using [bold yellow]{template.upper()}[/] template",
            expand=False,
        )
    )

    generator = Generator(root)

    # Progress for folders/files
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Generating project...", total=1)
        if template.lower() == "mvp":
            generator.generate_mvp()
        else:
            generator.generate_saas(db)
        progress.update(task, advance=1)

    # Extra optional files
    if gitignore:
        generator.write_file(
            root / ".gitignore", "__pycache__/\n.env\ninstance/\n*.pyc\n"
        )
    if readme:
        generator.write_file(
            root / "README.md", f"# {project_name}\n\nGenerated by FlaskIt CLI.\n"
        )
    if dockerfile:
        generator.write_file(
            root / "Dockerfile",
            f'FROM python:3.10-slim\nWORKDIR /{project_name}\nCOPY . .\nRUN pip install -r requirements.txt\nCMD ["python", "{entry_point}"]\n',
        )
    if env_file:
        db_line = (
            "DB_URL=postgresql://username:password@localhost:5432/dbname"
            if db == "postgresql"
            else "DB_URL=sqlite:///app.db"
        )
        generator.write_file(
            root / ".env",
            f"FLASK_APP={entry_point}\nFLASK_ENV=development\n{db_line}\n",
        )

    # Rich table summary
    table = Table(title="Generated Items")
    table.add_column("Type")
    table.add_column("Path")
    for emoji, path in generator.generated_items:
        table.add_row(emoji, path)
    console.print(table)

    console.print(
        Panel(
            f"✅ Project [bold cyan]{project_name}[/] ready! Start coding!",
            style="green",
        )
    )
    console.print(f"Next steps:\n  cd {project_name}\n  flaskit up")

    if vscode:
        # code = standard, code-oss = OSS builds on Linux, codium = VSCodium
        code_path = None
        for cmd in ("code", "code-oss", "codium"):
            code_path = shutil.which(cmd)
            if code_path:
                break
        if code_path:
            console.print(f"\n[bold cyan]Opening {project_name} in VS Code...[/]")
            if platform.system() == "Windows":
                subprocess.Popen(f'"{code_path}" "{root}"', shell=True)
            else:
                subprocess.Popen([code_path, str(root)])
        else:
            console.print(
                "\n[yellow]⚠️ VS Code command not found. Looked for: code, code-oss, codium.[/]"
            )
            console.print("[yellow]  Install VS Code and ensure it's on your PATH.[/]")


@app.command()
def demo():
    """Generate a hello-flaskit MVP project and run it instantly."""
    project = "hello-flaskit"
    root = Path(project).resolve()

    if root.exists():
        console.print(
            f"[yellow]⚠️ '{project}' already exists. Remove it first or run from another directory.[/]"
        )
        raise typer.Exit(1)

    console.print(
        Panel(
            "⚡ FlaskIt Demo — watch a project come to life in seconds",
            style="bold cyan",
            expand=False,
        )
    )

    # Generate the project
    generator = Generator(root)
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Scaffolding hello-flaskit...", total=1)
        generator.generate_mvp()
        progress.update(task, advance=1)

    console.print(f"\n[green]✅ Created {project}/ with MVP template[/]")

    # Check Flask is available
    flask_check = subprocess.run(
        [sys.executable, "-c", "import flask"], capture_output=True
    )
    if flask_check.returncode != 0:
        console.print("[yellow]⚠️ Flask is not installed. Installing...[/]")
        install = subprocess.run(
            [sys.executable, "-m", "pip", "install", "flask", "-q"], capture_output=True
        )
        if install.returncode != 0:
            console.print("[red]Could not install Flask automatically.[/]")
            console.print(
                f"[yellow]Install it manually, then run:[/]\n  cd {project}\n  python main.py"
            )
            raise typer.Exit(1)

    # Launch the dev server
    console.print(f"\n[bold cyan]Starting dev server → http://127.0.0.1:5000[/]")
    console.print("[dim]Press Ctrl+C to stop[/]\n")
    time.sleep(1)
    try:
        subprocess.run([sys.executable, str(root / "main.py")])
    except KeyboardInterrupt:
        console.print("\n[green]Server stopped. Your project is at:[/]")
        console.print(f"  cd {project}")


def get_venv_python(root: Path) -> Path:
    """Return the path to the Python executable inside the virtual environment."""
    if platform.system() == "Windows":
        return root / ".venv" / "Scripts" / "python.exe"
    return root / ".venv" / "bin" / "python"


def get_venv_pip(root: Path) -> Path:
    """Return the path to pip inside the virtual environment."""
    if platform.system() == "Windows":
        return root / ".venv" / "Scripts" / "pip.exe"
    return root / ".venv" / "bin" / "pip"


@app.command()
def up(
    skip_venv: bool = typer.Option(
        False, "--skip-venv", help="Skip virtual environment creation"
    ),
    skip_deps: bool = typer.Option(
        False, "--skip-deps", help="Skip dependency installation"
    ),
    skip_db: bool = typer.Option(
        False, "--skip-db", help="Skip database initialization"
    ),
    skip_migrate: bool = typer.Option(
        False, "--skip-migrate", help="Skip running migrations"
    ),
    no_server: bool = typer.Option(
        False, "--no-server", help="Don't start the development server"
    ),
):
    """Prepare and run a FlaskIt project for development.

    Creates virtual environment, installs dependencies, sets up .env,
    initializes database, runs migrations, and starts the dev server.
    """
    root = Path.cwd().resolve()
    total_steps = 6
    current_step = 0

    # Detect the entry point (MVP uses main.py, SAAS uses run.py)
    if (root / "run.py").exists():
        entry_point = "run.py"
        flask_app = "run:app"
    elif (root / "main.py").exists():
        entry_point = "main.py"
        flask_app = "main:app"
    else:
        console.print(
            "[red]❌ Error: No Flask entry point found (main.py or run.py)[/]"
        )
        console.print("[yellow]Make sure you're in a FlaskIt project directory.[/]")
        raise typer.Exit(1)

    venv_python = get_venv_python(root)

    # Step 1: Create virtual environment
    current_step += 1
    if not skip_venv:
        console.print(
            f"[bold cyan][{current_step}/{total_steps}][/] Creating virtual environment..."
        )
        venv_path = root / ".venv"
        if venv_path.exists():
            console.print("  [dim]Virtual environment already exists, skipping...[/]")
        else:
            try:
                import venv

                venv.create(venv_path, with_pip=True)
                console.print("  [green]✓[/] Virtual environment created")
            except Exception as e:
                console.print(f"[red]❌ Failed to create virtual environment: {e}[/]")
                raise typer.Exit(1)
    else:
        console.print(
            f"[dim][{current_step}/{total_steps}] Skipping virtual environment creation...[/]"
        )

    # Verify venv python exists
    if not venv_python.exists():
        console.print(
            f"[red]❌ Error: Virtual environment Python not found at {venv_python}[/]"
        )
        console.print(
            "[yellow]Try running without --skip-venv to create the virtual environment.[/]"
        )
        raise typer.Exit(1)

    # Step 2: Install dependencies
    current_step += 1
    if not skip_deps:
        console.print(
            f"[bold cyan][{current_step}/{total_steps}][/] Installing dependencies..."
        )
        requirements_file = root / "requirements.txt"
        if requirements_file.exists():
            # Optionally upgrade pip first
            console.print("  [dim]Upgrading pip...[/]")
            pip_upgrade = subprocess.run(
                [str(venv_python), "-m", "pip", "install", "--upgrade", "pip", "-q"],
                capture_output=True,
                text=True,
            )
            if pip_upgrade.returncode != 0:
                console.print(
                    f"  [yellow]⚠️ Could not upgrade pip: {pip_upgrade.stderr}[/]"
                )

            # Install requirements
            result = subprocess.run(
                [
                    str(venv_python),
                    "-m",
                    "pip",
                    "install",
                    "-r",
                    str(requirements_file),
                    "-q",
                ],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                console.print(f"[red]❌ Failed to install dependencies:[/]")
                console.print(f"[red]{result.stderr}[/]")
                raise typer.Exit(1)
            console.print("  [green]✓[/] Dependencies installed")
        else:
            # No requirements.txt, but Flask is required at minimum
            console.print("  [dim]No requirements.txt found, installing Flask...[/]")
            result = subprocess.run(
                [str(venv_python), "-m", "pip", "install", "flask", "-q"],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                console.print(f"[red]❌ Failed to install Flask:[/]")
                console.print(f"[red]{result.stderr}[/]")
                raise typer.Exit(1)
            console.print("  [green]✓[/] Flask installed")
    else:
        console.print(
            f"[dim][{current_step}/{total_steps}] Skipping dependency installation...[/]"
        )

    # Step 3: Create .env file
    current_step += 1
    console.print(f"[bold cyan][{current_step}/{total_steps}][/] Creating .env file...")
    env_file = root / ".env"
    env_example = root / ".env.example"
    if env_file.exists():
        console.print("  [dim].env file already exists, skipping...[/]")
    elif env_example.exists():
        try:
            shutil.copy(env_example, env_file)
            console.print("  [green]✓[/] .env created from .env.example")
        except Exception as e:
            console.print(f"[red]❌ Failed to create .env: {e}[/]")
            raise typer.Exit(1)
    else:
        # Create a basic .env file
        try:
            env_content = f"FLASK_APP={entry_point}\nFLASK_ENV=development\nSECRET_KEY=dev-secret-key\n"
            env_file.write_text(env_content)
            console.print("  [green]✓[/] Created basic .env file")
        except Exception as e:
            console.print(f"[red]❌ Failed to create .env: {e}[/]")
            raise typer.Exit(1)

    # Step 4: Initialize the database
    current_step += 1
    if not skip_db:
        console.print(
            f"[bold cyan][{current_step}/{total_steps}][/] Initializing database..."
        )
        # Check if Flask-SQLAlchemy is being used (look for extensions.py or db in imports)
        has_db = (root / "app" / "extensions.py").exists() or (
            root / "config.py"
        ).exists()
        if has_db:
            # For SQLite, just ensure the instance directory exists
            instance_dir = root / "instance"
            instance_dir.mkdir(exist_ok=True)

            # Check if db file exists or needs to be created via Flask
            # We'll attempt to init the db using Flask shell context
            init_db_script = """
from run import app
from app.extensions import db
with app.app_context():
    db.create_all()
    print('Database tables created')
"""
            if entry_point == "main.py":
                init_db_script = """
from app import app
try:
    from app.extensions import db
    with app.app_context():
        db.create_all()
        print('Database tables created')
except ImportError:
    print('No database extensions found, skipping')
"""
            result = subprocess.run(
                [str(venv_python), "-c", init_db_script],
                capture_output=True,
                text=True,
                cwd=str(root),
            )
            if result.returncode == 0:
                console.print(
                    f"  [green]✓[/] {result.stdout.strip() or 'Database initialized'}"
                )
            else:
                # Database init might fail if there's no SQLAlchemy, that's okay
                if (
                    "No module named" in result.stderr
                    or "cannot import" in result.stderr.lower()
                ):
                    console.print(
                        "  [dim]No database configuration found, skipping...[/]"
                    )
                else:
                    console.print(
                        f"  [yellow]⚠️ Database initialization warning: {result.stderr.strip()}[/]"
                    )
        else:
            console.print("  [dim]No database configuration detected, skipping...[/]")
    else:
        console.print(
            f"[dim][{current_step}/{total_steps}] Skipping database initialization...[/]"
        )

    # Step 5: Run migrations
    current_step += 1
    if not skip_migrate:
        console.print(
            f"[bold cyan][{current_step}/{total_steps}][/] Running migrations..."
        )
        migrations_dir = root / "migrations"
        if migrations_dir.exists():
            # Run flask db upgrade
            env = {**subprocess.os.environ, "FLASK_APP": flask_app}
            result = subprocess.run(
                [str(venv_python), "-m", "flask", "db", "upgrade"],
                capture_output=True,
                text=True,
                cwd=str(root),
                env=env,
            )
            if result.returncode == 0:
                console.print("  [green]✓[/] Migrations applied")
            else:
                console.print(
                    f"  [yellow]⚠️ Migration warning: {result.stderr.strip() or 'No migrations to apply'}[/]"
                )
        else:
            console.print("  [dim]No migrations directory found, skipping...[/]")
    else:
        console.print(f"[dim][{current_step}/{total_steps}] Skipping migrations...[/]")

    # Step 6: Start development server
    current_step += 1
    if not no_server:
        console.print(
            f"[bold cyan][{current_step}/{total_steps}][/] Starting development server..."
        )
        console.print(
            Panel(
                "[green]✓ FlaskIt project is running at http://127.0.0.1:5000[/]",
                expand=False,
            )
        )
        console.print("[dim]Press Ctrl+C to stop the server[/]\n")

        try:
            subprocess.run([str(venv_python), str(root / entry_point)], cwd=str(root))
        except KeyboardInterrupt:
            console.print("\n[green]✓ Server stopped.[/]")
    else:
        console.print(
            f"[dim][{current_step}/{total_steps}] Skipping server startup...[/]"
        )
        console.print(Panel("[green]✓ FlaskIt project is ready![/]", expand=False))
        console.print(f"\nTo start the server manually:\n  {venv_python} {entry_point}")


# Alias 'new' to 'create' for convenience
app.command("new")(create)


if __name__ == "__main__":
    app()
